/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface GeoChainFHEInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "badgeClaimed"
      | "claimBadge"
      | "confidentialProtocolId"
      | "getEncryptedResultScore"
      | "getEncryptedTotalScore"
      | "getMyEncryptedTotalScore"
      | "getPlayerStats"
      | "nextResultId"
      | "playerStats"
      | "submitResult"
      | "updateQuestionPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BadgeClaimed"
      | "QuestionPoolUpdated"
      | "ResultSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "badgeClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimBadge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedResultScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotalScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyEncryptedTotalScore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextResultId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "playerStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResult",
    values: [BytesLike, BytesLike, BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateQuestionPool",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "badgeClaimed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimBadge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedResultScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyEncryptedTotalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextResultId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateQuestionPool",
    data: BytesLike
  ): Result;
}

export namespace BadgeClaimedEvent {
  export type InputTuple = [
    player: AddressLike,
    badgeId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    badgeId: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    player: string;
    badgeId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestionPoolUpdatedEvent {
  export type InputTuple = [poolCID: string, version: BigNumberish];
  export type OutputTuple = [poolCID: string, version: bigint];
  export interface OutputObject {
    poolCID: string;
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultSubmittedEvent {
  export type InputTuple = [
    id: BigNumberish,
    player: AddressLike,
    resultHash: BytesLike,
    resultCID: string,
    scorePublic: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    player: string,
    resultHash: string,
    resultCID: string,
    scorePublic: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    player: string;
    resultHash: string;
    resultCID: string;
    scorePublic: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GeoChainFHE extends BaseContract {
  connect(runner?: ContractRunner | null): GeoChainFHE;
  waitForDeployment(): Promise<this>;

  interface: GeoChainFHEInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  badgeClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  claimBadge: TypedContractMethod<
    [badgeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getEncryptedResultScore: TypedContractMethod<
    [id: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedTotalScore: TypedContractMethod<
    [player: AddressLike],
    [string],
    "view"
  >;

  getMyEncryptedTotalScore: TypedContractMethod<[], [string], "view">;

  getPlayerStats: TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        numGames: bigint;
        totalPublicScore: bigint;
        maxSinglePublicScore: bigint;
        lastPlayedAt: bigint;
      }
    ],
    "view"
  >;

  nextResultId: TypedContractMethod<[], [bigint], "view">;

  playerStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        numGames: bigint;
        totalPublicScore: bigint;
        maxSinglePublicScore: bigint;
        lastPlayedAt: bigint;
      }
    ],
    "view"
  >;

  submitResult: TypedContractMethod<
    [
      scoreExt: BytesLike,
      inputProof: BytesLike,
      resultHash: BytesLike,
      resultCID: string,
      scorePublic: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  updateQuestionPool: TypedContractMethod<
    [poolCID: string, version: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "badgeClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimBadge"
  ): TypedContractMethod<[badgeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedResultScore"
  ): TypedContractMethod<[id: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotalScore"
  ): TypedContractMethod<[player: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMyEncryptedTotalScore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPlayerStats"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        numGames: bigint;
        totalPublicScore: bigint;
        maxSinglePublicScore: bigint;
        lastPlayedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextResultId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "playerStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        numGames: bigint;
        totalPublicScore: bigint;
        maxSinglePublicScore: bigint;
        lastPlayedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitResult"
  ): TypedContractMethod<
    [
      scoreExt: BytesLike,
      inputProof: BytesLike,
      resultHash: BytesLike,
      resultCID: string,
      scorePublic: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateQuestionPool"
  ): TypedContractMethod<
    [poolCID: string, version: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BadgeClaimed"
  ): TypedContractEvent<
    BadgeClaimedEvent.InputTuple,
    BadgeClaimedEvent.OutputTuple,
    BadgeClaimedEvent.OutputObject
  >;
  getEvent(
    key: "QuestionPoolUpdated"
  ): TypedContractEvent<
    QuestionPoolUpdatedEvent.InputTuple,
    QuestionPoolUpdatedEvent.OutputTuple,
    QuestionPoolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ResultSubmitted"
  ): TypedContractEvent<
    ResultSubmittedEvent.InputTuple,
    ResultSubmittedEvent.OutputTuple,
    ResultSubmittedEvent.OutputObject
  >;

  filters: {
    "BadgeClaimed(address,uint256,uint256)": TypedContractEvent<
      BadgeClaimedEvent.InputTuple,
      BadgeClaimedEvent.OutputTuple,
      BadgeClaimedEvent.OutputObject
    >;
    BadgeClaimed: TypedContractEvent<
      BadgeClaimedEvent.InputTuple,
      BadgeClaimedEvent.OutputTuple,
      BadgeClaimedEvent.OutputObject
    >;

    "QuestionPoolUpdated(string,uint256)": TypedContractEvent<
      QuestionPoolUpdatedEvent.InputTuple,
      QuestionPoolUpdatedEvent.OutputTuple,
      QuestionPoolUpdatedEvent.OutputObject
    >;
    QuestionPoolUpdated: TypedContractEvent<
      QuestionPoolUpdatedEvent.InputTuple,
      QuestionPoolUpdatedEvent.OutputTuple,
      QuestionPoolUpdatedEvent.OutputObject
    >;

    "ResultSubmitted(uint256,address,bytes32,string,uint256,uint256)": TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;
    ResultSubmitted: TypedContractEvent<
      ResultSubmittedEvent.InputTuple,
      ResultSubmittedEvent.OutputTuple,
      ResultSubmittedEvent.OutputObject
    >;
  };
}
